name: Team's Approval Workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    
    steps:
      - name: Automate Approvals 
      - uses: abinoda/TobKed/label-when-approved-action@main
      
        env:
          APPROVALS: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
